### ISSUE TITLE
Export improvement request

### ISSUE THREAD

**Issue by iss000** [teiram/oric-dsk-manager#2]
This is not an issues but request see [DF discussion](http://forum.defence-force.org/viewtopic.php?f=19&t=1804&p=22484#p22484).
Add options in 'File' menu to export selected file as TAP file and as plain binary.

**Comment by teiram** [comment]
Just released version 0.8 with support for the requested options

**Comment by iss000** [comment]
There is small bug in TAP export - the result TAP file is longer than actual size (it's padded with zeros).
FIX: Change in [TAPWriter.java line 50](https://github.com/teiram/oric-dsk-manager/blob/62720253f1c35de4724df1b7b47fdf51bb4067e2/src/main/java/com/grelobites/oric/dsk/util/TapWriter.java#L50) from:
`stream.write(archive.getData());`
to:
`stream.write(archive.getData(), 0, archive.getSize());`
creates correct TAP file.

And one more thing: under Linux 64 / KDE / GTK 
In [MainApp.java line 362](https://github.com/teiram/oric-dsk-manager/blob/62720253f1c35de4724df1b7b47fdf51bb4067e2/src/main/java/com/grelobites/oric/dsk/MainApp.java#L362) at start creates small window which can't be resized.
![bug](https://user-images.githubusercontent.com/1128663/83958128-d7e5f280-a876-11ea-87af-081ee4f8d96a.png)

As work around I commented line 362 and the window is OK (but remains resizable):
![no-bug](https://user-images.githubusercontent.com/1128663/83958156-24c9c900-a877-11ea-838c-c1b2b047f071.png)

Thanks for the great work!

**Comment by teiram** [comment]
Hello iss000. Thanks a lot for your feedback.
Regarding the padding zeroes problem, I tried to import and reexport a TAP file and didn't suffer the issue. Additionally, archive.getSize returns the size of the data array, so I think both should be equivalent. Could you provide the exact use case where you are suffering the problem?

Regarding the small window on KDE, could you please try with the version I'm attached here? I've provided a minimum size for the main frame instead of using computed sizes. Let's see if this fixes the issue (I have not the proper environment to test it myself)

[oric-dsk-manager-0.8.zip](https://github.com/teiram/oric-dsk-manager/files/4742839/oric-dsk-manager-0.8.zip)

**Comment by iss000** [comment]
Attached is 'Ultra' DSK version and extracted files:
- plain binary - 9151 - OK - exactly as reported in window;
- sedoric file - 9163 OK = 9151+12 bytes header;
- tap file using getSize - 9170 OK = 9151+19 bytes header;
- tap file by default - 9235 = 9151+19 bytes header + 65 extra zeros.

![tap-sizes](https://user-images.githubusercontent.com/1128663/83982905-f0b3de00-a932-11ea-85c2-41b04ab0ac44.png)

[ultra-tap-size-test.zip](https://github.com/teiram/oric-dsk-manager/files/4743281/ultra-tap-size-test.zip)

About the resize: I need help how to use files from 'oric-dsk-manager-0.8.zip' ?

**Comment by teiram** [comment]
Just rename the file back to jar and off you go. Let me know if it works properly and if not, please attach an screenshot of how it looks like.

Regarding the zero padding issue, seems you are right and in that case the reported size can be different than the array size (took from the sectors in the disk).

**Comment by iss000** [comment]
Unfortunately it didn't work - small window again:

![report-1](https://user-images.githubusercontent.com/1128663/84072062-42ae3f80-a9d7-11ea-8509-a786f06516d3.png)

**EDIT**: Interesting is that everything else works with shortcuts - Ctrl-O opens DSK file, but the window remains small.
